### ISSUE TITLE
Parametrization of tests

### ISSUE THREAD

**Issue by VascoSch92** [Diapolo10/iplib3#103]
Hey, 

first of all: very nice package and idea :-)

I was looking at the tests and I notice that you just have unit tests and not integration and/or acceptance tests. 

About the unit tests. There is a thing that can be done better and it is parametrisation. For instance, in a test you test multiple test cases using `assert`. This is not optimal. It would be better to have a script with the test cases and one with the tests, and use [pytest parametrisation](https://docs.pytest.org/en/7.3.x/how-to/parametrize.html).

If you want I could do it. I'm interested in understanding the package better, and this is a good opportunity to look deeply into your code and doing something good ;-)

let me know

**Comment by Diapolo10** [comment]
Apologies for the late reply, I've been busy with work lately and haven't had a good opportunity to touch this project for a good while. It's a bit of a mess and could use a major overhaul in general.

Feel free to do that if you want, I'll merge any pull requests that make sense.

**Comment by Diapolo10** [comment]
I don't know if it matters, but I originally started this project t help me remember things I learnt during a networking course. Later on I found out there's a virtually identical module in the standard library so in terms of practicality this project mostly just serves as a curiosity. I also tend to sometimes use it as an example when discussing topics on /r/learnpython.

I guess what I'm trying to say is, the project doesn't really serve a purpose, but it holds sentimental value to me as my first PyPI package.

**Comment by VascoSch92** [comment]
hey,

no problem. 
I just found the idea interesting and wanted to understand it a little bit more. The best thing to do when you want to learn how to use a python package is to use it ;-)
I did a PR on how I would structure the tests. I thought I would take a little less time but there are really a lot of tests :-P
